/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 gavel.glb 
*/

import { useGLTF } from '@react-three/drei';

export function Model(props) {
  const { nodes, materials } = useGLTF('src/assets/models/gavel.glb');
  return (
    <group {...props} dispose={null}>
      <group
        rotation={[Math.PI / 2, -Math.PI / 2, 0]}
        scale={[0.189, 0.176, 0.189]}
      >
        <mesh
          geometry={nodes.Circle004.geometry}
          material={materials['Material.003']}
        />
        <mesh
          geometry={nodes.Circle004_1.geometry}
          material={materials['Material.004']}
        />
        <mesh
          geometry={nodes.Circle004_2.geometry}
          material={materials['Material.005']}
        />
        <mesh
          geometry={nodes.Circle004_3.geometry}
          material={materials['Material.006']}
        />
        <mesh
          geometry={nodes.Circle004_4.geometry}
          material={materials['Material.007']}
        />
        <mesh
          geometry={nodes.Circle004_5.geometry}
          material={materials['Material.008']}
        />
        <mesh
          geometry={nodes.Circle004_6.geometry}
          material={materials['Material.009']}
        />
        <mesh
          geometry={nodes.Circle004_7.geometry}
          material={materials['Automotive led lights']}
        />
      </group>
    </group>
  );
}

useGLTF.preload('/gavel.glb');

// 기본 내보내기 추가
export default Model;
