/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 rolex.glb 
*/

import { useGLTF } from '@react-three/drei';

export function Rolex(props) {
  const { nodes, materials } = useGLTF('models/rolex.glb');
  return (
    <group {...props} dispose={null}>
      <group scale={0.019}>
        <mesh
          geometry={nodes.Circle.geometry}
          material={materials.meetal}
          position={[1.026, 2.776, 0.138]}
          rotation={[-Math.PI / 2, -0.254, Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Circle001.geometry}
          material={materials.meetal}
          position={[1.026, 2.776, 0.138]}
          rotation={[-Math.PI / 2, -0.254, Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Circle002.geometry}
          material={materials.meetal}
          position={[1.026, 2.776, 0.138]}
          rotation={[-Math.PI / 2, -0.254, Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Circle003.geometry}
          material={materials.meetal}
          position={[0.891, 3.484, -0.287]}
          rotation={[Math.PI / 2, 0.254, -Math.PI / 2]}
          scale={0.075}
        />
        <mesh
          geometry={nodes.Circle004.geometry}
          material={materials['meetal.001']}
          position={[0.577, 2.688, 0.138]}
          rotation={[Math.PI / 2, 0.254, -Math.PI / 2]}
          scale={1.293}
        />
        <mesh
          geometry={nodes.Circle005.geometry}
          material={materials.chrome}
          position={[0.558, 2.683, 0.138]}
          rotation={[Math.PI / 2, 0.254, -Math.PI / 2]}
          scale={[1.102, 1, 1.102]}
        />
        <mesh
          geometry={nodes.Circle006.geometry}
          material={materials['meetal.002']}
          position={[0.574, 2.687, 0.138]}
          rotation={[Math.PI / 2, 0.254, -Math.PI / 2]}
        />
        <group
          position={[1.026, 2.776, 0.138]}
          rotation={[-Math.PI / 2, -0.254, Math.PI / 2]}
        >
          <mesh
            geometry={nodes.Circle008_1.geometry}
            material={materials['Material.003']}
          />
          <mesh
            geometry={nodes.Circle008_2.geometry}
            material={materials['glossy black']}
          />
        </group>
        <mesh
          geometry={nodes.Circle008.geometry}
          material={materials['glossy black.001']}
          position={[1.064, 2.786, 0.138]}
          rotation={[-Math.PI / 2, -0.254, Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Circle009.geometry}
          material={materials.glass}
          position={[1.026, 2.776, 0.138]}
          rotation={[-Math.PI / 2, -0.254, Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Circle010.geometry}
          material={materials.meetal}
          position={[0.804, 2.746, -1.326]}
          rotation={[Math.PI / 2, 0.254, Math.PI]}
          scale={0.2}
        />
        <group
          position={[0.877, 4.017, 0.138]}
          rotation={[Math.PI / 2, 0.254, -Math.PI / 2]}
        >
          <mesh
            geometry={nodes.Circle013_1.geometry}
            material={materials.meetal}
          />
          <mesh
            geometry={nodes.Circle013_2.geometry}
            material={materials['Material.002']}
          />
        </group>
        <mesh
          geometry={nodes.Circle012.geometry}
          material={materials['Material.002']}
          position={[0.891, 3.484, -0.287]}
          rotation={[Math.PI / 2, 0.254, -Math.PI / 2]}
          scale={0.076}
        />
        <mesh
          geometry={nodes.Circle013.geometry}
          material={materials.meetal}
          position={[0.968, 3.189, -0.581]}
          rotation={[Math.PI / 2, 0.254, -Math.PI / 2]}
          scale={0.072}
        />
        <mesh
          geometry={nodes.Circle014.geometry}
          material={materials['Material.002']}
          position={[0.968, 3.189, -0.581]}
          rotation={[Math.PI / 2, 0.254, -Math.PI / 2]}
          scale={0.073}
        />
        <mesh
          geometry={nodes.Circle015.geometry}
          material={materials.meetal}
          position={[1.177, 2.381, -0.577]}
          rotation={[Math.PI / 2, 0.254, -Math.PI / 2]}
          scale={0.072}
        />
        <mesh
          geometry={nodes.Circle016.geometry}
          material={materials['Material.002']}
          position={[1.177, 2.381, -0.577]}
          rotation={[Math.PI / 2, 0.254, -Math.PI / 2]}
          scale={0.073}
        />
        <mesh
          geometry={nodes.Circle017.geometry}
          material={materials.meetal}
          position={[1.255, 2.082, -0.281]}
          rotation={[Math.PI / 2, 0.254, -Math.PI / 2]}
          scale={0.072}
        />
        <mesh
          geometry={nodes.Circle018.geometry}
          material={materials['Material.002']}
          position={[1.255, 2.082, -0.281]}
          rotation={[Math.PI / 2, 0.254, -Math.PI / 2]}
          scale={0.073}
        />
        <mesh
          geometry={nodes.Circle019.geometry}
          material={materials.meetal}
          position={[0.891, 3.484, 0.554]}
          rotation={[-Math.PI / 2, -0.254, Math.PI / 2]}
          scale={-0.075}
        />
        <mesh
          geometry={nodes.Circle020.geometry}
          material={materials['Material.002']}
          position={[0.891, 3.484, 0.554]}
          rotation={[-Math.PI / 2, -0.254, Math.PI / 2]}
          scale={-0.076}
        />
        <mesh
          geometry={nodes.Circle021.geometry}
          material={materials.meetal}
          position={[0.968, 3.189, 0.848]}
          rotation={[-Math.PI / 2, -0.254, Math.PI / 2]}
          scale={-0.072}
        />
        <mesh
          geometry={nodes.Circle022.geometry}
          material={materials['Material.002']}
          position={[0.968, 3.189, 0.848]}
          rotation={[-Math.PI / 2, -0.254, Math.PI / 2]}
          scale={-0.073}
        />
        <mesh
          geometry={nodes.Circle023.geometry}
          material={materials.meetal}
          position={[1.177, 2.383, 0.848]}
          rotation={[-Math.PI / 2, -0.254, Math.PI / 2]}
          scale={-0.072}
        />
        <mesh
          geometry={nodes.Circle024.geometry}
          material={materials['Material.002']}
          position={[1.177, 2.383, 0.848]}
          rotation={[-Math.PI / 2, -0.254, Math.PI / 2]}
          scale={-0.073}
        />
        <mesh
          geometry={nodes.Circle025.geometry}
          material={materials.meetal}
          position={[1.254, 2.084, 0.553]}
          rotation={[-Math.PI / 2, -0.254, Math.PI / 2]}
          scale={-0.072}
        />
        <mesh
          geometry={nodes.Circle026.geometry}
          material={materials['Material.002']}
          position={[1.254, 2.084, 0.553]}
          rotation={[-Math.PI / 2, -0.254, Math.PI / 2]}
          scale={-0.073}
        />
        <mesh
          geometry={nodes.Circle027.geometry}
          material={materials['Material.001']}
          position={[1.064, 2.786, 0.138]}
          rotation={[-Math.PI / 2, -0.254, Math.PI / 2]}
        />
        <group
          position={[1.132, 2.823, 0.147]}
          rotation={[Math.PI / 2, 0.254, -Math.PI / 2]}
          scale={0.055}
        >
          <mesh
            geometry={nodes.Circle042.geometry}
            material={materials.meetal}
          />
          <mesh
            geometry={nodes.Circle042_1.geometry}
            material={materials['Material.002']}
          />
        </group>
        <group
          position={[1.132, 2.823, 0.147]}
          rotation={[Math.PI / 2, 0.254, -Math.PI / 2]}
          scale={0.055}
        >
          <mesh
            geometry={nodes.Circle043.geometry}
            material={materials.meetal}
          />
          <mesh
            geometry={nodes.Circle043_1.geometry}
            material={materials['Material.002']}
          />
        </group>
        <group
          position={[1.132, 2.823, 0.147]}
          rotation={[Math.PI / 2, 0.254, -Math.PI / 2]}
          scale={0.055}
        >
          <mesh
            geometry={nodes.Circle044.geometry}
            material={materials.meetal}
          />
          <mesh
            geometry={nodes.Circle044_1.geometry}
            material={materials['Material.002']}
          />
        </group>
        <mesh
          geometry={nodes.Circle031.geometry}
          material={materials.chrome}
          position={[-0.162, 4.597, -0.478]}
          rotation={[-Math.PI / 2, 1.086, 0]}
          scale={[0.825, 0.934, 0.825]}
        />
        <mesh
          geometry={nodes.Circle032.geometry}
          material={materials.chrome}
          position={[-0.162, 4.597, 0.748]}
          rotation={[Math.PI / 2, -1.086, Math.PI]}
          scale={[-0.825, -0.934, -0.825]}
        />
        <mesh
          geometry={nodes.crown.geometry}
          material={materials.meetal}
          position={[-2.082, 1.221, 0.137]}
          rotation={[-Math.PI / 2, -0.472, -Math.PI / 2]}
          scale={[7.135, 3.798, 7.135]}
        />
        <mesh
          geometry={nodes.crown001.geometry}
          material={materials.meetal}
          position={[0.795, 2.801, -1.583]}
          rotation={[-1.592, -0.3, -0.006]}
          scale={-4.147}
        />
        <mesh
          geometry={nodes.Cube.geometry}
          material={materials.meetal}
          position={[0.817, 2.75, 0.138]}
          rotation={[Math.PI / 2, 0.254, -Math.PI / 2]}
          scale={[1.518, 1.674, 1.674]}
        />
        <mesh
          geometry={nodes.Cube001.geometry}
          material={materials.meetal}
          position={[0.817, 2.75, 0.138]}
          rotation={[Math.PI / 2, 0.254, -Math.PI / 2]}
          scale={[1.518, 1.674, 1.674]}
        />
        <mesh
          geometry={nodes.Cube002.geometry}
          material={materials.meetal}
          position={[0.574, 2.687, 0.138]}
          rotation={[Math.PI / 2, 0.254, -Math.PI / 2]}
          scale={[0.123, 0.192, 0.123]}
        />
        <mesh
          geometry={nodes.Cube003.geometry}
          material={materials.meetal}
          position={[0.574, 2.687, 0.138]}
          rotation={[Math.PI / 2, 0.254, -Math.PI / 2]}
          scale={[0.123, 0.192, 0.123]}
        />
        <mesh
          geometry={nodes.Cube004.geometry}
          material={materials.meetal}
          position={[0.574, 2.687, 0.138]}
          rotation={[Math.PI / 2, 0.254, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Cube005.geometry}
          material={materials.meetal}
          position={[0.574, 2.687, 0.138]}
          rotation={[Math.PI / 2, 0.254, -Math.PI / 2]}
          scale={[0.123, 0.192, 0.123]}
        />
        <mesh
          geometry={nodes.Cube006.geometry}
          material={materials.meetal}
          position={[0.574, 2.687, 0.138]}
          rotation={[Math.PI / 2, 0.254, -Math.PI / 2]}
          scale={[0.123, 0.192, 0.123]}
        />
        <mesh
          geometry={nodes.Cube007.geometry}
          material={materials.meetal}
          position={[0.579, 2.667, 0.138]}
          rotation={[Math.PI / 2, 0.254, -Math.PI / 2]}
          scale={[0.123, 0.192, 0.123]}
        />
        <mesh
          geometry={nodes.Cube008.geometry}
          material={materials.meetal}
          position={[0.574, 2.687, 0.138]}
          rotation={[Math.PI / 2, 0.254, -Math.PI / 2]}
          scale={[0.123, 0.192, 0.123]}
        />
        <mesh
          geometry={nodes.Cube009.geometry}
          material={materials.meetal}
          position={[0.574, 2.687, 0.138]}
          rotation={[Math.PI / 2, 0.254, -Math.PI / 2]}
          scale={[0.123, 0.192, 0.123]}
        />
        <mesh
          geometry={nodes.Cube010.geometry}
          material={materials.meetal}
          position={[0.574, 2.687, 0.138]}
          rotation={[Math.PI / 2, 0.254, -Math.PI / 2]}
          scale={[0.123, 0.192, 0.123]}
        />
        <mesh
          geometry={nodes.Cube011.geometry}
          material={materials.meetal}
          position={[0.574, 2.687, 0.138]}
          rotation={[Math.PI / 2, 0.254, -Math.PI / 2]}
          scale={[0.123, 0.192, 0.123]}
        />
        <mesh
          geometry={nodes.Cube012.geometry}
          material={materials.meetal}
          position={[0.574, 2.687, 0.138]}
          rotation={[Math.PI / 2, 0.254, -Math.PI / 2]}
          scale={[0.123, 0.192, 0.123]}
        />
        <mesh
          geometry={nodes.Cube013.geometry}
          material={materials.meetal}
          position={[0.574, 2.687, 0.138]}
          rotation={[Math.PI / 2, 0.254, -Math.PI / 2]}
          scale={[0.123, 0.192, 0.123]}
        />
        <mesh
          geometry={nodes.Cube014.geometry}
          material={materials.meetal}
          position={[0.574, 2.687, 0.138]}
          rotation={[Math.PI / 2, 0.254, -Math.PI / 2]}
          scale={[0.123, 0.192, 0.123]}
        />
        <mesh
          geometry={nodes.Cube016.geometry}
          material={materials.meetal}
          position={[0.574, 2.687, 0.138]}
          rotation={[Math.PI / 2, 0.254, -Math.PI / 2]}
          scale={[0.123, 0.192, 0.123]}
        />
        <mesh
          geometry={nodes.Cube019.geometry}
          material={materials.meetal}
          position={[0.574, 2.687, 0.138]}
          rotation={[Math.PI / 2, 0.254, -Math.PI / 2]}
          scale={[0.123, 0.192, 0.123]}
        />
        <mesh
          geometry={nodes.Cube020.geometry}
          material={materials.meetal}
          position={[0.574, 2.687, 0.138]}
          rotation={[Math.PI / 2, 0.254, -Math.PI / 2]}
          scale={[0.123, 0.192, 0.123]}
        />
        <mesh
          geometry={nodes.Cylinder.geometry}
          material={materials.meetal}
          position={[1.105, 2.816, 0.147]}
          rotation={[Math.PI / 2, 0.254, -Math.PI / 2]}
          scale={-0.015}
        />
        <mesh
          geometry={nodes.Plane001.geometry}
          material={materials.meetal}
          position={[-2.177, 2.058, 0.137]}
          rotation={[Math.PI / 2, 0.24, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Plane002.geometry}
          material={materials.meetal}
          position={[-1.822, 1.587, 0.126]}
          rotation={[Math.PI / 2, 0.458, -Math.PI / 2]}
          scale={[0.582, 1, 1]}
        />
        <mesh
          geometry={nodes.Plane003.geometry}
          material={materials.meetal}
          position={[-1.822, 1.587, 0.126]}
          rotation={[Math.PI / 2, 0.458, -Math.PI / 2]}
          scale={[0.582, 1, 1]}
        />
        <mesh
          geometry={nodes.Plane004.geometry}
          material={materials.meetal}
          position={[-1.824, 1.587, 0.126]}
          rotation={[Math.PI / 2, 0.458, -Math.PI / 2]}
          scale={[0.582, 1, 1]}
        />
        <mesh
          geometry={nodes.Plane005.geometry}
          material={materials['Material.002']}
          position={[0.852, 3.651, 0.121]}
          rotation={[Math.PI / 2, 0.254, -Math.PI / 2]}
          scale={[0.035, 0.031, 0.031]}
        />
        <mesh
          geometry={nodes.Plane006.geometry}
          material={materials.meetal}
          position={[0.852, 3.651, 0.121]}
          rotation={[Math.PI / 2, 0.254, -Math.PI / 2]}
          scale={[0.908, 0.796, 0.796]}
        />
        <mesh
          geometry={nodes.Plane007.geometry}
          material={materials['glass.001']}
          position={[1.202, 2.807, -0.542]}
          rotation={[Math.PI / 2, 0.254, -Math.PI / 2]}
          scale={[-0.184, -0.248, -0.196]}
        />
        <mesh
          geometry={nodes.Plane008.geometry}
          material={materials.meetal}
          position={[-2.177, 2.058, 0.137]}
          rotation={[Math.PI / 2, 0.24, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Plane009.geometry}
          material={materials['Material.002']}
          position={[1.076, 2.785, 0.885]}
          rotation={[-Math.PI / 2, -0.254, Math.PI / 2]}
          scale={[-0.144, -0.136, -0.05]}
        />
        <mesh
          geometry={nodes.Plane010.geometry}
          material={materials.meetal}
          position={[1.073, 2.784, 0.885]}
          rotation={[-Math.PI / 2, -0.254, Math.PI / 2]}
          scale={[-1.094, -1.094, -1.077]}
        />
        <mesh
          geometry={nodes.Plane011.geometry}
          material={materials['Material.002']}
          position={[1.263, 2.064, 0.145]}
          rotation={[Math.PI, 0, 1.317]}
          scale={[-0.144, -0.136, -0.042]}
        />
        <mesh
          geometry={nodes.Plane012.geometry}
          material={materials.meetal}
          position={[1.263, 2.064, 0.145]}
          rotation={[-Math.PI, 0, 1.317]}
          scale={[-1.094, -1.094, -0.912]}
        />
      </group>
    </group>
  );
}

useGLTF.preload('./rolex.glb');

export default Rolex;
